### PR TITLE
Set up package with multiple outputs

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

@thewchan, is this a horrible idea? :laughing:

### CODE REVIEW

**Comment by maresb** [comment]
I got a +1 from mbecker, assuming that the versions are pinned.

I have asked on dbt Slack (#dbt-core-development) whether the version numbers of the plugins will remain pinned to dbt-core. The answer there should decide which approach is better.

**Comment by maresb** [comment]
No further feedback from dbt; maybe they're not sure themselves!

I'm inclined to go ahead with this multiple outputs recipe for now. Then if the plugins diverge in the future, then we can split them off.

What do you think @drewbanin, @jthandy, @thewchan?

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Note: this PR inserts me as a maintainer

**Comment by thewchan** [comment]
@maresb I vote we go for it!

**Comment by maresb** [comment]
@thewchan 

Just a few minutes too late to influence this decision, I received this over Slack from Jeremy Cohen (jerco):

> Hi Ben, great question, and great timing to be asking it!
After v1, we're planning to slightly loosen the version coupling of dbt Labs-maintained adapter plugins. The major + minor versions will keep matching, but patch releases can be independent. So it will be possible to use (e.g.) dbt-core==1.0.2 with dbt-snowflake==1.0.1
We're encouraging maintainers of community- and vendor-supported adapter plugins to adopt the same versioning scheme, but it's ultimately up to them of course
A bit more about this here: https://discourse.getdbt.com/t/prerelease-dbt-core-v1-0-0-beta/3180#plugins-4

Maybe it's possible to somehow relax the pin, and then if there's an important plugin update, we just bump the build number. That would result in some superfluous builds for the unchanged packages, but then if something is evolving faster we could always split it off later as needed.

**Pull request merged**
