### PR TITLE
Add requirements

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
```text
nothing provides requested mashumaro 2.5.*
```
https://github.com/conda-forge/mashumaro-feedstock

**Comment by maresb** [comment]
Once masumaro 2.5 hits the CDN we can restart the CI.

**Comment by thewchan** [comment]
@conda-forge-admin, please restart ci

**Comment by maresb** [comment]
I'm replacing this PR with dbt-core https://github.com/conda-forge/staged-recipes/pull/16709

**Pull request closed without merging**
