### PR TITLE
Release just dbt-core and dbt-postgres v1.1.1

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@thewchan, what do you think of this? And then we make separate feedstocks as described in #66 like https://github.com/conda-forge/staged-recipes/pull/16710.

**Comment by maresb** [comment]
The remaining packages are to be added by https://github.com/conda-forge/staged-recipes/pull/19517

**Comment by thewchan** [comment]
@maresb I think this looks good!

**Comment by maresb** [comment]
Thanks @thewchan! I will merge now.

Could you please comment over at https://github.com/conda-forge/staged-recipes/pull/19517 to say you're willing to be a maintainer?

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
